indicators:
  - key: "SAMPLE-0001"
    description: "Total Childrean"
    indicatorQuery: "select count(*) from indicator_queries"

  - key: "SAMPLE-0002"
    description: "Total immunized"
    indicatorQuery: "select count(*) from indicator_queries"

  - key: "SAMPLE-0003"
    description: "Total not immunized"
    indicatorQuery: "select count(*) from indicator_queries"
