indicators:
  - key: "S_IND_001"
    description: "Total Childrean"
    indicatorQuery: "select count(*) from indicator_queries"

  - key: "S_IND_002"
    description: "Total immunized"
    indicatorQuery: "select count(*) from indicator_queries"

  - key: "S_IND_003"
    description: "Total not immunized"
    indicatorQuery: "select count(*) from indicator_queries"
